// @ts-nocheck
// ILLUSTRATIVE ONLY — this file does NOT compile in issue #1044.
// The materialized module `.yakcc/atoms/0009c5df8b58.ts` is created by `yakcc build`
// (#1045). The `.d.ts` stub that makes the import typecheck before a full build is
// created by the .d.ts pass (#1046). The MCP tool that emits this import line for the
// model is implemented in #1047.
//
// This file shows the in-source reference format produced by yakcc_reference (#1047):
// a single cheap import line (~10 tokens) that replaces writing the full implementation
// (~100–500 tokens). The `alias` (12-char prefix of the BlockMerkleRoot) is the only
// token that appears in source; the full 64-char root lives once in .yakcc/manifest.json.

// @decision DEC-COMPOSE-BY-REF-MANIFEST-001
// The import line below is the canonical in-source reference format.
// Generated by: referenceImportLine(ref) from @yakcc/compile/project-manifest
import { crc32c } from "../.yakcc/atoms/0009c5df8b58.js";

// Trivial usage of the imported symbol to complete the illustration:
export function crc32cWrapper(data: Uint8Array): number {
  return crc32c(data);
}
