// SPDX-License-Identifier: MIT
//
// bench/B7-commit/harness/run.mjs
//
// @decision DEC-BENCH-B7-HARNESS-001
// @title B7-commit harness: novel-glue flywheel round-trip latency (Slice 1)
// @status accepted (WI-B7-SLICE-1, issue #381)
// @rationale
//   TIMING METHODOLOGY
//   Three timestamps capture each emission's round-trip cost:
//     t0_emit   — immediately before atomizeEmission() is called
//     t2_atomized — immediately after atomizeEmission() resolves
//     t3_query_hit — immediately after findCandidatesByIntent() resolves
//   wallMs = t3_query_hit - t0_emit (full round-trip wall-clock in ms).
//   Date.now() is used (not performance.now()) for simplicity and JSON serializability.
//   The 50-measurement set (5 utilities × 2 cache states × 5 reps) is intentionally
//   small — this is a KILL-gate check, not a statistically rigorous benchmark.
//
//   REGISTRY ISOLATION
//   Cold runs: a fresh SQLite registry is created for each rep, closed and deleted
//   after the measurement. This ensures zero state bleeds between cold measurements.
//   Warm runs: a single SQLite registry is created per utility (opened before rep 1,
//   reused for reps 2–5, closed after rep 5). The first rep in a warm sequence is
//   effectively cold for that utility; subsequent reps query a registry that already
//   contains the just-stored atom. This is a deliberate choice — see WARM-CACHE NOTE.
//
//   WARM-CACHE NOTE (DEC-BENCH-B7-HARNESS-001)
//   The issue spec offered two warm-cache definitions:
//     (a) Pre-warmed registry with a 100-atom set committed to the repo.
//     (b) Reuse the same registry across the N=5 reps for each utility.
//   This implementation uses option (b), the simpler approach. Rationale:
//   - Option (a) requires a committed sqlite artifact (binary, large) and a deterministic
//     seed script. This adds repo weight and CI complexity.
//   - Option (b) is self-consistent: the warm path has the just-stored atom in cache,
//     which is the most relevant warm state for the flywheel (the atom was just created
//     by this session).
//   - If warm-cache definition becomes load-bearing for the verdict, Slice 2 can add
//     option (a) and compare. For now, option (b) produces the most optimistic warm
//     estimate, which is the correct direction for a KILL-gate: if warm > 15s with
//     the optimistic definition, option (a) would be even slower.
//   This deviation from the plan's preference for option (a) is documented here so
//   Future Implementers can switch to option (a) in Slice 2 without confusion.
//
//   PRE-CANNED SOURCE
//   Corpus files under bench/B7-commit/corpus/ are hand-authored TypeScript utilities.
//   They are read from disk rather than generated by a live LLM. The live-LLM emission
//   variant is deferred to a hypothetical B7b. Pre-canned source avoids non-determinism
//   in the benchmark and removes the Anthropic API key requirement (B6 preserved).
//
//   OFFLINE / STATIC STRATEGY
//   atomizeEmission is called with intentStrategy: "static" and offline: true (the
//   defaults in atomize.ts). This uses pure AST analysis via ts-morph — no HTTP,
//   no Anthropic API, no outbound network calls. B6 air-gap is preserved.
//
// Cross-reference:
//   DEC-BENCH-METHODOLOGY-NEVER-SYNTHETIC-001 (oracle is real shaved content, not LLM-generated)
//   bench/v0-release-smoke/smoke.mjs Steps 8b + 9 (proved the round-trip works)
//   bench/B6-airgap/ (SHA-256 corpus verification pattern mirrored here)
//
// Usage:
//   node bench/B7-commit/harness/run.mjs
//   pnpm bench:commit

import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Repo root resolution (mirrors v0-release-smoke pattern)
// ---------------------------------------------------------------------------

function resolveRepoRoot() {
  if (process.env.YAKCC_REPO_ROOT) return process.env.YAKCC_REPO_ROOT;
  let dir = __dirname;
  for (let i = 0; i < 10; i++) {
    const pkg = join(dir, "package.json");
    if (existsSync(pkg)) {
      try {
        const p = JSON.parse(readFileSync(pkg, "utf8"));
        if (p.name === "yakcc") return dir;
      } catch (_) {}
    }
    const parent = resolve(dir, "..");
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: two levels up from harness/
  return resolve(__dirname, "../../..");
}

const REPO_ROOT = resolveRepoRoot();

/**
 * Convert a filesystem path to an ESM-importable URL string.
 * On Windows, bare paths like "C:\..." are invalid for ESM import() —
 * Node.js requires file:// URLs. On POSIX, pathToFileURL still works correctly.
 */
function pathToImportUrl(fsPath) {
  return pathToFileURL(fsPath).href;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const N_REPS = 5;
const TOP_K = 5;
const CONFIDENT_THRESHOLD = 0.70;

const CORPUS_DIR = join(__dirname, "..", "corpus");
const CORPUS_SPEC_PATH = join(__dirname, "..", "corpus-spec.json");
const BENCH_DIR = __dirname; // bench/B7-commit/harness/
const ARTIFACT_DIR = join(REPO_ROOT, "tmp", "B7-commit");
const SCRATCH_DIR = join(REPO_ROOT, "tmp", "B7-commit", "scratch");

const TIMESTAMP = new Date().toISOString().replace(/[:.]/g, "-");
const ARTIFACT_PATH = join(ARTIFACT_DIR, `slice1-${TIMESTAMP}.json`);

// ---------------------------------------------------------------------------
// Step 0: Verify corpus SHA-256 integrity
// ---------------------------------------------------------------------------

function verifyCorpusIntegrity() {
  console.log("[B7] Verifying corpus SHA-256 integrity...");
  const spec = JSON.parse(readFileSync(CORPUS_SPEC_PATH, "utf8"));

  for (const entry of spec.files) {
    const filePath = join(CORPUS_DIR, entry.filename);
    if (!existsSync(filePath)) {
      throw new Error(`Corpus file missing: ${filePath}`);
    }
    const content = readFileSync(filePath);
    const actual = createHash("sha256").update(content).digest("hex");
    if (actual !== entry.sha256) {
      throw new Error(
        `SHA-256 drift detected for ${entry.filename}:\n` +
        `  expected: ${entry.sha256}\n` +
        `  actual:   ${actual}\n` +
        "Corpus is modified. Abort."
      );
    }
    console.log(`  [OK] ${entry.filename} — sha256=${actual.slice(0, 16)}...`);
  }

  console.log(`[B7] Corpus OK — ${spec.files.length} files verified.\n`);
  return spec;
}

// ---------------------------------------------------------------------------
// Registry helpers
// ---------------------------------------------------------------------------

async function loadRegistry(registryDist) {
  const { openRegistry } = await import(pathToImportUrl(registryDist));
  return { openRegistry };
}

// ---------------------------------------------------------------------------
// Core measurement: one (utility × cacheState × rep) observation
// ---------------------------------------------------------------------------

/**
 * Measure a single round-trip for a utility under a given cache state.
 *
 * Returns { wallMs, t0_emit, t2_atomized, t3_query_hit, atomized, bmrInTopK, combinedScore, bmr, candidateCount }
 */
async function measureOneRep({
  utilityName,
  emittedCode,
  intent,
  registry,
  atomizeEmission,
}) {
  // t0: immediately before atomizeEmission
  const t0_emit = Date.now();

  const atomizeResult = await atomizeEmission({
    emittedCode,
    toolName: "Write",
    registry,
  });

  // t2: immediately after atomizeEmission
  const t2_atomized = Date.now();

  const atomized = atomizeResult.atomized === true;
  const bmr =
    atomized && atomizeResult.atomsCreated.length > 0
      ? atomizeResult.atomsCreated[0].blockMerkleRoot
      : null;

  // Query the registry for the just-stored atom
  const intentQuery = {
    behavior: intent,
    inputs: [],
    outputs: [],
  };

  const candidates = await registry.findCandidatesByIntent(intentQuery, { k: TOP_K });

  // t3: immediately after findCandidatesByIntent
  const t3_query_hit = Date.now();

  // Verify BMR is in top-K and compute combined score
  let bmrInTopK = false;
  let combinedScore = 0;

  if (candidates.length > 0) {
    const returnedBmrs = candidates.map((c) => c.block.blockMerkleRoot);
    bmrInTopK = bmr !== null && returnedBmrs.some((b) => b === bmr);

    // combinedScore = 1 - cosineDistance^2 / 4
    // (same formula as hooks-base's candidatesToCombinedScores)
    const top = candidates[0];
    combinedScore = Math.max(0, Math.min(1, 1 - (top.cosineDistance * top.cosineDistance) / 4));
  }

  const wallMs = t3_query_hit - t0_emit;

  return {
    wallMs,
    t0_emit,
    t2_atomized,
    t3_query_hit,
    atomized,
    bmr: bmr ? bmr.slice(0, 16) : null,
    bmrInTopK,
    combinedScore,
    candidateCount: candidates.length,
    reason: atomized ? undefined : (atomizeResult.reason ?? "unknown"),
  };
}

// ---------------------------------------------------------------------------
// Median + p95 computation
// ---------------------------------------------------------------------------

function computeAggregate(values) {
  if (values.length === 0) return { median: null, p95: null };
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  const median =
    sorted.length % 2 === 0
      ? (sorted[mid - 1] + sorted[mid]) / 2
      : sorted[mid];
  const p95Idx = Math.ceil(sorted.length * 0.95) - 1;
  const p95 = sorted[Math.max(0, p95Idx)];
  return { median, p95 };
}

// ---------------------------------------------------------------------------
// Verdict gate
// ---------------------------------------------------------------------------

function computeVerdict(medianWarmMs) {
  if (medianWarmMs === null) {
    return {
      medianWarmMs: null,
      slice_1_call_to_action:
        "PASS-provisional — N=5 too small for final verdict; proceed to Slice 2",
      note: "No warm measurements succeeded (all atomized=false). Check atomize log.",
    };
  }

  const medianWarmS = medianWarmMs / 1000;

  if (medianWarmS <= 3) {
    return {
      medianWarmMs,
      medianWarmS: medianWarmS.toFixed(3),
      slice_1_call_to_action:
        "PASS-aspirational — median warm ≤3 s; proceed to Slice 2",
    };
  } else if (medianWarmS <= 10) {
    return {
      medianWarmMs,
      medianWarmS: medianWarmS.toFixed(3),
      slice_1_call_to_action:
        "PASS-hard-cap — median warm 3–10 s; proceed to Slice 2",
    };
  } else if (medianWarmS <= 15) {
    return {
      medianWarmMs,
      medianWarmS: medianWarmS.toFixed(3),
      slice_1_call_to_action:
        "WARN — median warm 10–15 s; proceed to Slice 2 with caution; consider filing WI-FAST-PATH-VERIFIER",
    };
  } else {
    return {
      medianWarmMs,
      medianWarmS: medianWarmS.toFixed(3),
      slice_1_call_to_action:
        "KILL — file WI-FAST-PATH-VERIFIER immediately",
    };
  }
}

// ---------------------------------------------------------------------------
// Main harness
// ---------------------------------------------------------------------------

async function main() {
  console.log("=".repeat(70));
  console.log("B7-commit — Slice 1: Novel-Glue Flywheel Round-Trip Latency");
  console.log("=".repeat(70));
  console.log();

  // 0. Verify corpus integrity
  const spec = verifyCorpusIntegrity();

  // 1. Resolve dist paths
  const registryDist = join(REPO_ROOT, "packages", "registry", "dist", "index.js");
  const hooksBaseDist = join(REPO_ROOT, "packages", "hooks-base", "dist", "index.js");

  if (!existsSync(registryDist)) {
    throw new Error(
      `@yakcc/registry dist not found at ${registryDist}.\n` +
      "Run `pnpm build` before executing the harness."
    );
  }
  if (!existsSync(hooksBaseDist)) {
    throw new Error(
      `@yakcc/hooks-base dist not found at ${hooksBaseDist}.\n` +
      "Run `pnpm build` before executing the harness."
    );
  }

  const { openRegistry } = await import(pathToImportUrl(registryDist));

  // atomizeEmission is not re-exported on the @yakcc/hooks-base index — import
  // directly from the atomize sub-module. This mirrors how the internal hook code
  // itself does the lazy import: `await import("./atomize.js")`.
  const hooksBaseAtomizeDist = join(REPO_ROOT, "packages", "hooks-base", "dist", "atomize.js");
  if (!existsSync(hooksBaseAtomizeDist)) {
    throw new Error(
      `@yakcc/hooks-base atomize dist not found at ${hooksBaseAtomizeDist}.\n` +
      "Run `pnpm build` before executing the harness."
    );
  }
  const { atomizeEmission } = await import(pathToImportUrl(hooksBaseAtomizeDist));

  // 2. Prepare scratch and artifact directories
  mkdirSync(ARTIFACT_DIR, { recursive: true });
  mkdirSync(SCRATCH_DIR, { recursive: true });

  // 3. Collect measurements
  const measurements = [];

  for (const fileEntry of spec.files) {
    const { filename, intent } = fileEntry;
    const utilityName = filename.replace(/\.ts$/, "");
    const corpusPath = join(CORPUS_DIR, filename);
    const emittedCode = readFileSync(corpusPath, "utf8");

    console.log(`\n[B7] Utility: ${utilityName}`);
    console.log(`     Intent: ${intent.slice(0, 80)}${intent.length > 80 ? "..." : ""}`);

    // --- WARM runs: single registry reused across N reps ---
    const warmRegistryPath = join(SCRATCH_DIR, `warm-${utilityName}.sqlite`);
    // Remove any leftover from a previous run
    if (existsSync(warmRegistryPath)) {
      rmSync(warmRegistryPath, { force: true });
    }
    const warmRegistry = await openRegistry(warmRegistryPath);

    for (let rep = 1; rep <= N_REPS; rep++) {
      process.stdout.write(`  [warm] rep ${rep}/${N_REPS}... `);
      const obs = await measureOneRep({
        utilityName,
        emittedCode,
        intent,
        registry: warmRegistry,
        atomizeEmission,
      });
      console.log(
        `${obs.wallMs}ms | atomized=${obs.atomized} bmrInTopK=${obs.bmrInTopK} ` +
        `score=${obs.combinedScore.toFixed(4)} candidates=${obs.candidateCount}` +
        (obs.reason ? ` reason=${obs.reason}` : "")
      );
      measurements.push({
        cacheState: "warm",
        utilityName,
        rep,
        ...obs,
      });
    }

    await warmRegistry.close();

    // --- COLD runs: fresh registry per rep ---
    for (let rep = 1; rep <= N_REPS; rep++) {
      process.stdout.write(`  [cold] rep ${rep}/${N_REPS}... `);
      const coldRegistryPath = join(SCRATCH_DIR, `cold-${utilityName}-rep${rep}.sqlite`);
      if (existsSync(coldRegistryPath)) {
        rmSync(coldRegistryPath, { force: true });
      }
      const coldRegistry = await openRegistry(coldRegistryPath);

      const obs = await measureOneRep({
        utilityName,
        emittedCode,
        intent,
        registry: coldRegistry,
        atomizeEmission,
      });
      console.log(
        `${obs.wallMs}ms | atomized=${obs.atomized} bmrInTopK=${obs.bmrInTopK} ` +
        `score=${obs.combinedScore.toFixed(4)} candidates=${obs.candidateCount}` +
        (obs.reason ? ` reason=${obs.reason}` : "")
      );

      await coldRegistry.close();

      measurements.push({
        cacheState: "cold",
        utilityName,
        rep,
        ...obs,
      });
    }
  }

  // 4. Aggregate
  const warmMeasurements = measurements.filter((m) => m.cacheState === "warm");
  const coldMeasurements = measurements.filter((m) => m.cacheState === "cold");

  const warmWallMs = warmMeasurements.map((m) => m.wallMs);
  const coldWallMs = coldMeasurements.map((m) => m.wallMs);

  const warmAggregate = computeAggregate(warmWallMs);
  const coldAggregate = computeAggregate(coldWallMs);

  // Count atomization successes
  const warmAtomized = warmMeasurements.filter((m) => m.atomized).length;
  const warmBmrInTopK = warmMeasurements.filter((m) => m.bmrInTopK).length;
  const warmConfident = warmMeasurements.filter((m) => m.combinedScore >= CONFIDENT_THRESHOLD).length;

  // Collect failures (non-atomized or BMR not in top-K)
  const failures = measurements.filter(
    (m) => !m.atomized || !m.bmrInTopK || m.combinedScore < CONFIDENT_THRESHOLD
  );

  // 5. Verdict
  const verdict = computeVerdict(warmAggregate.median);

  // Also compute median for warm measurements only where atomized+bmrInTopK (qualifying)
  const qualifyingWarmMs = warmMeasurements
    .filter((m) => m.atomized && m.bmrInTopK)
    .map((m) => m.wallMs);
  const qualifyingAggregate = computeAggregate(qualifyingWarmMs);
  const qualifyingVerdict = computeVerdict(qualifyingAggregate.median);

  // 6. Print summary
  console.log("\n" + "=".repeat(70));
  console.log("RESULTS SUMMARY");
  console.log("=".repeat(70));
  console.log();
  console.log(`Total measurements: ${measurements.length}`);
  console.log(`  Warm: ${warmMeasurements.length} | Cold: ${coldMeasurements.length}`);
  console.log();
  console.log("Warm cache stats:");
  console.log(`  median wallMs: ${warmAggregate.median?.toFixed(1) ?? "N/A"}`);
  console.log(`  p95 wallMs:    ${warmAggregate.p95?.toFixed(1) ?? "N/A"}`);
  console.log(`  atomized: ${warmAtomized}/${warmMeasurements.length}`);
  console.log(`  BMR in top-K: ${warmBmrInTopK}/${warmMeasurements.length}`);
  console.log(`  score >= ${CONFIDENT_THRESHOLD}: ${warmConfident}/${warmMeasurements.length}`);
  console.log();
  console.log("Cold cache stats:");
  console.log(`  median wallMs: ${coldAggregate.median?.toFixed(1) ?? "N/A"}`);
  console.log(`  p95 wallMs:    ${coldAggregate.p95?.toFixed(1) ?? "N/A"}`);
  console.log();
  if (qualifyingAggregate.median !== null && qualifyingAggregate.median !== warmAggregate.median) {
    console.log("Qualifying warm (atomized + BMR in top-K) stats:");
    console.log(`  median wallMs: ${qualifyingAggregate.median?.toFixed(1) ?? "N/A"}`);
    console.log(`  p95 wallMs:    ${qualifyingAggregate.p95?.toFixed(1) ?? "N/A"}`);
    console.log();
  }

  if (failures.length > 0) {
    console.log(`Failures (atomized=false OR bmrNotInTopK OR score<${CONFIDENT_THRESHOLD}):`);
    for (const f of failures) {
      console.log(
        `  [${f.cacheState}] ${f.utilityName} rep${f.rep}: ` +
        `atomized=${f.atomized} bmrInTopK=${f.bmrInTopK} ` +
        `score=${f.combinedScore.toFixed(4)}` +
        (f.reason ? ` reason=${f.reason}` : "")
      );
    }
    console.log();
  }

  console.log("VERDICT (all warm measurements):");
  console.log(`  ${verdict.slice_1_call_to_action}`);
  if (qualifyingAggregate.median !== null) {
    console.log();
    console.log("VERDICT (qualifying warm only — atomized + BMR in top-K):");
    console.log(`  ${qualifyingVerdict.slice_1_call_to_action}`);
  }
  console.log();

  // 7. Write artifact JSON
  const artifact = {
    benchmark: "B7-commit-slice1",
    version: "1.0.0",
    environment: {
      platform: process.platform,
      arch: process.arch,
      nodeVersion: process.version,
      runAt: new Date().toISOString(),
      repoRoot: REPO_ROOT,
    },
    config: {
      nReps: N_REPS,
      topK: TOP_K,
      confidentThreshold: CONFIDENT_THRESHOLD,
      warmCacheDefinition: "reuse same SQLite registry across N reps per utility (option b, optimistic)",
      intentStrategy: "static",
      offline: true,
    },
    corpus: spec,
    measurements,
    aggregate: {
      warm: {
        ...warmAggregate,
        atomizedCount: warmAtomized,
        bmrInTopKCount: warmBmrInTopK,
        confidentCount: warmConfident,
        totalReps: warmMeasurements.length,
      },
      cold: {
        ...coldAggregate,
        totalReps: coldMeasurements.length,
      },
      qualifyingWarm: {
        ...qualifyingAggregate,
        totalReps: qualifyingWarmMs.length,
      },
    },
    verdict,
    qualifyingVerdict,
    failures,
  };

  writeFileSync(ARTIFACT_PATH, JSON.stringify(artifact, null, 2), "utf8");
  console.log(`Artifact written to: ${ARTIFACT_PATH}`);

  // 8. Check acceptance criteria violations (hard assertions)
  const errors = [];

  // All utilities must atomize
  for (const utilityEntry of spec.files) {
    const utilityName = utilityEntry.filename.replace(/\.ts$/, "");
    const utilityMeasurements = measurements.filter((m) => m.utilityName === utilityName);
    const anyAtomized = utilityMeasurements.some((m) => m.atomized);
    if (!anyAtomized) {
      errors.push(
        `ACCEPTANCE VIOLATION: ${utilityName} — atomized=false for ALL measurements. ` +
        "Every utility must produce atomized=true. Check shave pipeline."
      );
    }
  }

  // BMR must be in top-K for qualifying (warm + atomized) measurements
  const failingBmrChecks = measurements.filter(
    (m) => m.atomized && !m.bmrInTopK
  );
  if (failingBmrChecks.length > 0) {
    for (const f of failingBmrChecks) {
      errors.push(
        `ACCEPTANCE VIOLATION: ${f.utilityName} [${f.cacheState}] rep${f.rep} — ` +
        `atomized=true but BMR not in top-K (candidates=${f.candidateCount}). ` +
        "Registry round-trip broken."
      );
    }
  }

  if (errors.length > 0) {
    console.error("\n" + "!".repeat(70));
    console.error("ACCEPTANCE CRITERIA VIOLATIONS — DO NOT MERGE");
    console.error("!".repeat(70));
    for (const e of errors) {
      console.error(`  ERROR: ${e}`);
    }
    console.error("\nFix the violations above before declaring WI-B7-SLICE-1 complete.");
    // Exit with non-zero code so the shell caller knows something is wrong
    process.exit(1);
  }

  console.log("[B7] All acceptance criteria met.");
  console.log("[B7] Done.");
}

main().catch((err) => {
  console.error("[B7] Fatal error:", err);
  process.exit(1);
});
