// SPDX-License-Identifier: MIT
/**
 * Emit a fast-check test file from a PropertySpec.
 *
 * @decision DEC-POLYGLOT-PROOF-IR-001 (see proof-properties.ts header)
 * @scope Single source of truth: proof-properties.ts. This file is one of two
 *   emitters (the other is hypothesis.ts). Behavioral equivalence between the
 *   two emitters is the load-bearing property exercised by their test suites.
 */

import type {
  AssertionDef,
  AssertionValue,
  GeneratorDef,
  PropertySpec,
} from "../proof-properties.js";

/**
 * Emit the contents of a `tests.fast-check.ts` file that exercises the named
 * function against the spec's properties.
 *
 * The emitted file imports `fc` from "fast-check" and the target function
 * from "./impl.js". Tests are deterministic-by-default (no seed override).
 */
export function emitFastCheckTests(spec: PropertySpec, fnName: string): string {
  const lines: string[] = [];
  lines.push("// AUTOGENERATED by @yakcc/contracts emitFastCheckTests.");
  lines.push("// Source of truth: proof/properties.json (DEC-POLYGLOT-PROOF-IR-001).");
  lines.push("// Do not edit by hand — regenerate from the spec.");
  lines.push('import * as fc from "fast-check";');
  lines.push('import { describe, it } from "vitest";');
  lines.push(`import { ${fnName} } from "./impl.js";`);
  lines.push("");
  lines.push(`describe(${JSON.stringify(fnName)}, () => {`);
  for (const p of spec.properties) {
    lines.push(`  it(${JSON.stringify(p.name)}, () => {`);
    lines.push("    fc.assert(");
    lines.push("      fc.property(");
    for (const inp of p.inputs) {
      lines.push(`        ${emitFcGenerator(inp.generator)},`);
    }
    const params = p.inputs.map((i) => i.name).join(", ");
    lines.push(`        (${params}) => {`);
    for (const line of emitFcAssertion(p.assertion, fnName, p.inputs.map((i) => i.name))) {
      lines.push(`          ${line}`);
    }
    lines.push("        },");
    lines.push("      ),");
    lines.push("    );");
    lines.push("  });");
  }
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

function emitFcGenerator(g: GeneratorDef): string {
  switch (g.kind) {
    case "integer": {
      const opts = bounds(g.min, g.max);
      return opts === "" ? "fc.integer()" : `fc.integer(${opts})`;
    }
    case "float": {
      const opts = bounds(g.min, g.max);
      return opts === "" ? "fc.float()" : `fc.float(${opts})`;
    }
    case "string": {
      const opts = stringBounds(g.minLength, g.maxLength);
      return opts === "" ? "fc.string()" : `fc.string(${opts})`;
    }
    case "boolean":
      return "fc.boolean()";
    case "array": {
      const item = emitFcGenerator(g.items);
      const opts = stringBounds(g.minLength, g.maxLength);
      return opts === "" ? `fc.array(${item})` : `fc.array(${item}, ${opts})`;
    }
    case "record": {
      const entries = Object.entries(g.fields)
        .map(([k, v]) => `${JSON.stringify(k)}: ${emitFcGenerator(v)}`)
        .join(", ");
      return `fc.record({ ${entries} })`;
    }
    case "tuple":
      return `fc.tuple(${g.items.map(emitFcGenerator).join(", ")})`;
    case "oneof":
      return `fc.oneof(${g.options.map(emitFcGenerator).join(", ")})`;
  }
}

function bounds(min?: number, max?: number): string {
  if (min === undefined && max === undefined) return "";
  const parts: string[] = [];
  if (min !== undefined) parts.push(`min: ${String(min)}`);
  if (max !== undefined) parts.push(`max: ${String(max)}`);
  return `{ ${parts.join(", ")} }`;
}

function stringBounds(minLength?: number, maxLength?: number): string {
  if (minLength === undefined && maxLength === undefined) return "";
  const parts: string[] = [];
  if (minLength !== undefined) parts.push(`minLength: ${String(minLength)}`);
  if (maxLength !== undefined) parts.push(`maxLength: ${String(maxLength)}`);
  return `{ ${parts.join(", ")} }`;
}

function emitFcAssertion(a: AssertionDef, fnName: string, inputNames: readonly string[]): string[] {
  const call = `${fnName}(${inputNames.join(", ")})`;
  switch (a.kind) {
    case "eq":
      return [`if (!(${call} === ${valueExpr(a.expected)})) throw new Error("eq violated");`];
    case "neq":
      return [`if (!(${call} !== ${valueExpr(a.expected)})) throw new Error("neq violated");`];
    case "lt":
      return [`if (!(${call} < ${valueExpr(a.expected)})) throw new Error("lt violated");`];
    case "lte":
      return [`if (!(${call} <= ${valueExpr(a.expected)})) throw new Error("lte violated");`];
    case "gt":
      return [`if (!(${call} > ${valueExpr(a.expected)})) throw new Error("gt violated");`];
    case "gte":
      return [`if (!(${call} >= ${valueExpr(a.expected)})) throw new Error("gte violated");`];
    case "throws": {
      const errCheck = a.errorClass
        ? ` if (!(e instanceof ${a.errorClass})) throw new Error("wrong error class");`
        : "";
      return [
        `let threw = false;`,
        `try { ${call}; } catch (e) {${errCheck} threw = true; }`,
        `if (!threw) throw new Error("expected throw");`,
      ];
    }
    case "not_throws":
      return [
        `try { ${call}; } catch { throw new Error("not_throws violated"); }`,
      ];
    case "custom_ir":
      return [
        `// custom_ir: ${a.description ?? a.predicate}`,
        `const _out = ${call};`,
        `if (!((${a.predicate}))) throw new Error("custom_ir violated");`,
      ];
  }
}

function valueExpr(v: AssertionValue): string {
  if (v.kind === "literal") {
    return JSON.stringify(v.value);
  }
  return v.name;
}
