import { describe, expect, it } from "vitest";
import type { PropertySpec } from "../proof-properties.js";
import { emitFastCheckTests } from "./fast-check.js";

const FN = "addOne";

describe("emitFastCheckTests", () => {
  it("emits a header naming the spec and imports fast-check + vitest", () => {
    const out = emitFastCheckTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "trivial",
            inputs: [],
            assertion: { kind: "not_throws" },
          },
        ],
      },
      FN,
    );
    expect(out).toContain("AUTOGENERATED");
    expect(out).toContain("DEC-POLYGLOT-PROOF-IR-001");
    expect(out).toContain('import * as fc from "fast-check"');
    expect(out).toContain('import { describe, it } from "vitest"');
    expect(out).toContain(`import { ${FN} } from "./impl.js"`);
    expect(out).toContain(`describe(${JSON.stringify(FN)},`);
  });

  it("emits integer generator with bounds when given", () => {
    const out = emitFastCheckTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "p",
            inputs: [{ name: "x", generator: { kind: "integer", min: 0, max: 100 } }],
            assertion: { kind: "not_throws" },
          },
        ],
      },
      FN,
    );
    expect(out).toContain("fc.integer({ min: 0, max: 100 })");
  });

  it("emits every generator kind", () => {
    const spec: PropertySpec = {
      schemaVersion: 1,
      properties: [
        {
          name: "all",
          inputs: [
            { name: "i", generator: { kind: "integer" } },
            { name: "f", generator: { kind: "float" } },
            { name: "s", generator: { kind: "string", maxLength: 5 } },
            { name: "b", generator: { kind: "boolean" } },
            { name: "a", generator: { kind: "array", items: { kind: "integer" } } },
            {
              name: "r",
              generator: { kind: "record", fields: { k: { kind: "boolean" } } },
            },
            {
              name: "t",
              generator: { kind: "tuple", items: [{ kind: "integer" }, { kind: "string" }] },
            },
            {
              name: "o",
              generator: {
                kind: "oneof",
                options: [{ kind: "integer" }, { kind: "string" }],
              },
            },
          ],
          assertion: { kind: "not_throws" },
        },
      ],
    };
    const out = emitFastCheckTests(spec, FN);
    expect(out).toContain("fc.integer()");
    expect(out).toContain("fc.float()");
    expect(out).toContain("fc.string({ maxLength: 5 })");
    expect(out).toContain("fc.boolean()");
    expect(out).toContain("fc.array(fc.integer())");
    expect(out).toContain('fc.record({ "k": fc.boolean() })');
    expect(out).toContain("fc.tuple(fc.integer(), fc.string())");
    expect(out).toContain("fc.oneof(fc.integer(), fc.string())");
  });

  it("emits each structured assertion form", () => {
    for (const [kind, op] of [
      ["eq", "==="],
      ["neq", "!=="],
      ["lt", "<"],
      ["lte", "<="],
      ["gt", ">"],
      ["gte", ">="],
    ] as const) {
      const out = emitFastCheckTests(
        {
          schemaVersion: 1,
          properties: [
            {
              name: kind,
              inputs: [{ name: "x", generator: { kind: "integer" } }],
              assertion: { kind, expected: { kind: "literal", value: 0 } },
            },
          ],
        },
        FN,
      );
      expect(out).toContain(`${FN}(x) ${op} 0`);
    }
  });

  it("emits throws with optional errorClass", () => {
    const out = emitFastCheckTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "p",
            inputs: [],
            assertion: { kind: "throws", errorClass: "TypeError" },
          },
        ],
      },
      FN,
    );
    expect(out).toContain("instanceof TypeError");
    expect(out).toContain('expected throw');
  });

  it("emits custom_ir predicate verbatim", () => {
    const out = emitFastCheckTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "monotonic",
            inputs: [{ name: "x", generator: { kind: "integer" } }],
            assertion: {
              kind: "custom_ir",
              predicate: "_out >= x",
              description: "output is at least the input",
            },
          },
        ],
      },
      FN,
    );
    expect(out).toContain("_out >= x");
    expect(out).toContain("output is at least the input");
  });

  it("uses input_ref name without quoting in the assertion", () => {
    const out = emitFastCheckTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "p",
            inputs: [{ name: "x", generator: { kind: "integer" } }],
            assertion: { kind: "eq", expected: { kind: "input_ref", name: "x" } },
          },
        ],
      },
      FN,
    );
    expect(out).toContain(`${FN}(x) === x`);
  });
});
