import { describe, expect, it } from "vitest";
import type { PropertySpec } from "../proof-properties.js";
import { emitHypothesisTests } from "./hypothesis.js";

const TS_FN = "addOne";
const PY_FN = "add_one";

describe("emitHypothesisTests", () => {
  it("emits a header and the hypothesis/pytest imports", () => {
    const out = emitHypothesisTests(
      {
        schemaVersion: 1,
        properties: [
          { name: "trivial", inputs: [], assertion: { kind: "not_throws" } },
        ],
      },
      TS_FN,
      PY_FN,
    );
    expect(out).toContain("AUTOGENERATED");
    expect(out).toContain("DEC-POLYGLOT-PROOF-IR-001");
    expect(out).toContain("from hypothesis import given, strategies as st");
    expect(out).toContain("import pytest");
    expect(out).toContain(`from .impl import ${PY_FN}`);
  });

  it("uses snake_case-compatible test names", () => {
    const out = emitHypothesisTests(
      {
        schemaVersion: 1,
        properties: [
          { name: "round-trip", inputs: [], assertion: { kind: "not_throws" } },
        ],
      },
      TS_FN,
      PY_FN,
    );
    expect(out).toContain("def test_addOne_round_trip(");
  });

  it("emits hypothesis strategies for every generator kind", () => {
    const spec: PropertySpec = {
      schemaVersion: 1,
      properties: [
        {
          name: "all",
          inputs: [
            { name: "i", generator: { kind: "integer", min: 0, max: 10 } },
            { name: "f", generator: { kind: "float" } },
            { name: "s", generator: { kind: "string", maxLength: 5 } },
            { name: "b", generator: { kind: "boolean" } },
            { name: "a", generator: { kind: "array", items: { kind: "integer" } } },
            {
              name: "r",
              generator: { kind: "record", fields: { k: { kind: "boolean" } } },
            },
            {
              name: "t",
              generator: { kind: "tuple", items: [{ kind: "integer" }, { kind: "string" }] },
            },
            {
              name: "o",
              generator: {
                kind: "oneof",
                options: [{ kind: "integer" }, { kind: "string" }],
              },
            },
          ],
          assertion: { kind: "not_throws" },
        },
      ],
    };
    const out = emitHypothesisTests(spec, TS_FN, PY_FN);
    expect(out).toContain("st.integers(min_value=0, max_value=10)");
    expect(out).toContain("st.floats(allow_nan=False, allow_infinity=False)");
    expect(out).toContain("st.text(max_size=5)");
    expect(out).toContain("st.booleans()");
    expect(out).toContain("st.lists(st.integers())");
    expect(out).toContain('st.fixed_dictionaries({"k": st.booleans()})');
    expect(out).toContain("st.tuples(st.integers(), st.text())");
    expect(out).toContain("st.one_of(st.integers(), st.text())");
  });

  it("emits each structured assertion as a Python `assert`", () => {
    for (const [kind, op] of [
      ["eq", "=="],
      ["neq", "!="],
      ["lt", "<"],
      ["lte", "<="],
      ["gt", ">"],
      ["gte", ">="],
    ] as const) {
      const out = emitHypothesisTests(
        {
          schemaVersion: 1,
          properties: [
            {
              name: kind,
              inputs: [{ name: "x", generator: { kind: "integer" } }],
              assertion: { kind, expected: { kind: "literal", value: 0 } },
            },
          ],
        },
        TS_FN,
        PY_FN,
      );
      expect(out).toContain(`assert ${PY_FN}(x) ${op} 0`);
    }
  });

  it("emits throws as pytest.raises with optional errorClass (defaults to Exception)", () => {
    const out1 = emitHypothesisTests(
      {
        schemaVersion: 1,
        properties: [
          { name: "p", inputs: [], assertion: { kind: "throws", errorClass: "ValueError" } },
        ],
      },
      TS_FN,
      PY_FN,
    );
    expect(out1).toContain("with pytest.raises(ValueError)");
    const out2 = emitHypothesisTests(
      {
        schemaVersion: 1,
        properties: [
          { name: "p", inputs: [], assertion: { kind: "throws" } },
        ],
      },
      TS_FN,
      PY_FN,
    );
    expect(out2).toContain("with pytest.raises(Exception)");
  });

  it("translates literal None/True/False correctly", () => {
    const out = emitHypothesisTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "null",
            inputs: [{ name: "x", generator: { kind: "boolean" } }],
            assertion: { kind: "eq", expected: { kind: "literal", value: null } },
          },
          {
            name: "true",
            inputs: [{ name: "x", generator: { kind: "boolean" } }],
            assertion: { kind: "eq", expected: { kind: "literal", value: true } },
          },
          {
            name: "false",
            inputs: [{ name: "x", generator: { kind: "boolean" } }],
            assertion: { kind: "eq", expected: { kind: "literal", value: false } },
          },
        ],
      },
      TS_FN,
      PY_FN,
    );
    expect(out).toContain(`assert ${PY_FN}(x) == None`);
    expect(out).toContain(`assert ${PY_FN}(x) == True`);
    expect(out).toContain(`assert ${PY_FN}(x) == False`);
  });

  it("custom_ir predicate is emitted verbatim inside an assert", () => {
    const out = emitHypothesisTests(
      {
        schemaVersion: 1,
        properties: [
          {
            name: "monotonic",
            inputs: [{ name: "x", generator: { kind: "integer" } }],
            assertion: {
              kind: "custom_ir",
              predicate: "_out >= x",
              description: "output is at least the input",
            },
          },
        ],
      },
      TS_FN,
      PY_FN,
    );
    expect(out).toContain("_out >= x");
    expect(out).toContain("output is at least the input");
  });

  it("cross-emitter coverage: every generator/assertion kind round-trips through both emitters", () => {
    const spec: PropertySpec = {
      schemaVersion: 1,
      properties: [
        {
          name: "eq",
          inputs: [{ name: "x", generator: { kind: "integer" } }],
          assertion: { kind: "eq", expected: { kind: "input_ref", name: "x" } },
        },
        {
          name: "neq",
          inputs: [{ name: "x", generator: { kind: "string" } }],
          assertion: { kind: "neq", expected: { kind: "literal", value: "" } },
        },
        {
          name: "throws",
          inputs: [],
          assertion: { kind: "throws", errorClass: "TypeError" },
        },
        { name: "nt", inputs: [], assertion: { kind: "not_throws" } },
        {
          name: "ci",
          inputs: [{ name: "x", generator: { kind: "integer" } }],
          assertion: { kind: "custom_ir", predicate: "_out > 0" },
        },
      ],
    };
    // Both emitters accept the same spec without throwing.
    const ts = emitHypothesisTests(spec, TS_FN, PY_FN);
    expect(ts.length).toBeGreaterThan(0);
    // Spot-check that the predicate appears in the Python output unchanged.
    expect(ts).toContain("_out > 0");
  });
});
