// SPDX-License-Identifier: MIT
/**
 * Emit a hypothesis (Python) test file from a PropertySpec.
 *
 * @decision DEC-POLYGLOT-PROOF-IR-001 (see proof-properties.ts header)
 * @scope Sibling of fast-check.ts; both consume the same PropertySpec so that
 *   regenerated Python tests behave equivalently to the TS fast-check tests.
 *   Cross-emitter equivalence is the load-bearing test the suite asserts via
 *   structural coverage (each generator/assertion kind round-trips through
 *   both emitters with a stable, snapshot-matched output).
 */

import type {
  AssertionDef,
  AssertionValue,
  GeneratorDef,
  PropertySpec,
} from "../proof-properties.js";

/**
 * Emit the contents of a `tests.hypothesis.py` file that exercises the named
 * Python function (camelCase TS name → snake_case Python name handled by
 * caller via the explicit pyFnName argument).
 */
export function emitHypothesisTests(
  spec: PropertySpec,
  fnName: string,
  pyFnName: string,
): string {
  const lines: string[] = [];
  lines.push("# AUTOGENERATED by @yakcc/contracts emitHypothesisTests.");
  lines.push("# Source of truth: proof/properties.json (DEC-POLYGLOT-PROOF-IR-001).");
  lines.push("# Do not edit by hand - regenerate from the spec.");
  lines.push("from hypothesis import given, strategies as st");
  lines.push("import pytest");
  lines.push(`from .impl import ${pyFnName}`);
  lines.push("");
  for (const p of spec.properties) {
    const decorators: string[] = [];
    for (const inp of p.inputs) {
      decorators.push(`@given(${inp.name}=${emitHypGenerator(inp.generator)})`);
    }
    for (const d of decorators) {
      lines.push(d);
    }
    const safeName = sanitizePyName(`test_${fnName}_${p.name}`);
    const params = p.inputs.map((i) => i.name).join(", ");
    lines.push(`def ${safeName}(${params}):`);
    const body = emitHypAssertion(p.assertion, pyFnName, p.inputs.map((i) => i.name));
    for (const line of body) {
      lines.push(`    ${line}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function emitHypGenerator(g: GeneratorDef): string {
  switch (g.kind) {
    case "integer":
      return `st.integers(${kvBounds("min_value", g.min, "max_value", g.max)})`;
    case "float":
      return `st.floats(${kvBounds("min_value", g.min, "max_value", g.max, true)})`;
    case "string":
      return `st.text(${kvBounds("min_size", g.minLength, "max_size", g.maxLength)})`;
    case "boolean":
      return "st.booleans()";
    case "array":
      return `st.lists(${emitHypGenerator(g.items)}${kvBoundsSuffix("min_size", g.minLength, "max_size", g.maxLength)})`;
    case "record": {
      const entries = Object.entries(g.fields)
        .map(([k, v]) => `${pyStr(k)}: ${emitHypGenerator(v)}`)
        .join(", ");
      return `st.fixed_dictionaries({${entries}})`;
    }
    case "tuple":
      return `st.tuples(${g.items.map(emitHypGenerator).join(", ")})`;
    case "oneof":
      return `st.one_of(${g.options.map(emitHypGenerator).join(", ")})`;
  }
}

function kvBounds(
  minKey: string,
  minVal: number | undefined,
  maxKey: string,
  maxVal: number | undefined,
  allowNanInf?: boolean,
): string {
  const parts: string[] = [];
  if (minVal !== undefined) parts.push(`${minKey}=${String(minVal)}`);
  if (maxVal !== undefined) parts.push(`${maxKey}=${String(maxVal)}`);
  if (allowNanInf) {
    parts.push("allow_nan=False", "allow_infinity=False");
  }
  return parts.join(", ");
}

function kvBoundsSuffix(
  minKey: string,
  minVal: number | undefined,
  maxKey: string,
  maxVal: number | undefined,
): string {
  const parts: string[] = [];
  if (minVal !== undefined) parts.push(`${minKey}=${String(minVal)}`);
  if (maxVal !== undefined) parts.push(`${maxKey}=${String(maxVal)}`);
  if (parts.length === 0) return "";
  return `, ${parts.join(", ")}`;
}

function emitHypAssertion(
  a: AssertionDef,
  pyFnName: string,
  inputNames: readonly string[],
): string[] {
  const call = `${pyFnName}(${inputNames.join(", ")})`;
  switch (a.kind) {
    case "eq":
      return [`assert ${call} == ${pyValueExpr(a.expected)}`];
    case "neq":
      return [`assert ${call} != ${pyValueExpr(a.expected)}`];
    case "lt":
      return [`assert ${call} < ${pyValueExpr(a.expected)}`];
    case "lte":
      return [`assert ${call} <= ${pyValueExpr(a.expected)}`];
    case "gt":
      return [`assert ${call} > ${pyValueExpr(a.expected)}`];
    case "gte":
      return [`assert ${call} >= ${pyValueExpr(a.expected)}`];
    case "throws": {
      const exc = a.errorClass ?? "Exception";
      return [`with pytest.raises(${exc}):`, `    ${call}`];
    }
    case "not_throws":
      return [
        "try:",
        `    ${call}`,
        "except Exception as e:",
        '    raise AssertionError(f"not_throws violated: {e!r}")',
      ];
    case "custom_ir":
      return [
        `# custom_ir: ${a.description ?? a.predicate}`,
        `_out = ${call}`,
        `assert (${a.predicate}), "custom_ir violated"`,
      ];
  }
}

function pyValueExpr(v: AssertionValue): string {
  if (v.kind === "literal") {
    if (v.value === null) return "None";
    if (typeof v.value === "boolean") return v.value ? "True" : "False";
    if (typeof v.value === "string") return pyStr(v.value);
    return String(v.value);
  }
  return v.name;
}

function pyStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function sanitizePyName(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, "_");
}
