// SPDX-License-Identifier: MIT
//
// @decision DEC-COMPOSE-BY-REF-DTS-001
// title: atom-dts — .d.ts generator derived from SpecYak (not from impl)
// status: decided (#1046, epic #1043 [3/6])
// rationale:
//   The compose-by-reference design (DEC-V3-DISCOVERY-D4-001) lets source files
//   import a referenced atom BEFORE `yakcc build` materialises the implementation.
//   For TypeScript to typecheck those imports, a `.d.ts` declaration file must exist
//   at `.yakcc/atoms/<alias>.d.ts` (materializedDtsPath). The declaration is derived
//   entirely from the atom's SpecYak signature — it does NOT require the impl.ts to
//   exist, which is the key property: reference source typechecks pre-build.
//
//   The .d.ts is the "typed half" of compose-by-reference:
//     - The .d.ts is generated here from spec signature → `export declare function`
//     - The impl.ts is generated by `yakcc build` (#1045) → `export function` + body
//
//   Authority: alias → path mapping is owned exclusively by `materializedDtsPath`
//   from project-manifest.ts (DEC-COMPOSE-BY-REF-MANIFEST-001). No path derivation
//   is re-implemented here.
//
//   Consumed by:
//     - `yakcc build` (#1045 / #1046): writes this text alongside the .ts
//     - `yakcc_reference` MCP tool (#1047): reads it for the caller's type surface
//
//   Forbidden shortcuts per Evaluation Contract:
//     - Do NOT derive the .d.ts by emitting from the full impl (must work pre-build)
//     - No silent fallback on missing or malformed spec: throw loud Error

import type { SpecYak } from "@yakcc/contracts";

// ---------------------------------------------------------------------------
// Public surface
// ---------------------------------------------------------------------------

/**
 * Generate the `.d.ts` text for an atom given its SpecYak specification and
 * the bound export symbol name.
 *
 * The generated text declares the atom's entry function as:
 *   `export declare function <symbol>(<inputs>): <returnType>;`
 *
 * Return-type mapping:
 *   - 0 outputs → `void`
 *   - 1 output  → that output's `type` string (e.g. `string`, `number`)
 *   - N outputs → tuple `[t0, t1, …]` of their `type` strings
 *     (simplest faithful mapping; spec imposes no named-tuple obligation at L0)
 *
 * Input name synthesis: if an input has an empty (or missing) `name`, the
 * generator synthesises `arg0`, `arg1`, … positionally.
 *
 * Throws a loud `Error` on a malformed spec (missing `inputs`/`outputs` arrays,
 * or an empty `symbol`). No silent defaults — DEC-COMPOSE-BY-REF-DTS-001.
 *
 * @param spec   - The atom's SpecYak, typically from registry block specCanonicalBytes.
 * @param symbol - The bound export name the source imports (e.g. "asciiChar").
 *                 May differ from spec.name (e.g. spec.name = "ascii-char").
 * @returns Deterministic `.d.ts` text ending with a trailing newline.
 *
 * @decision DEC-COMPOSE-BY-REF-DTS-001
 */
export function generateAtomDts(spec: SpecYak, symbol: string): string {
  // ---- guard: loud failure on malformed inputs ----

  if (!symbol || typeof symbol !== "string") {
    throw new Error(
      `generateAtomDts: symbol must be a non-empty string, got ${JSON.stringify(symbol)}`,
    );
  }

  if (!Array.isArray(spec.inputs)) {
    throw new Error(
      `generateAtomDts: spec.inputs must be an array (spec.name = ${JSON.stringify(spec.name)})`,
    );
  }

  if (!Array.isArray(spec.outputs)) {
    throw new Error(
      `generateAtomDts: spec.outputs must be an array (spec.name = ${JSON.stringify(spec.name)})`,
    );
  }

  // ---- build the parameter list ----

  const paramList = spec.inputs
    .map((p, i) => {
      // Synthesise arg0, arg1, … when name is absent or empty.
      const name = typeof p.name === "string" && p.name.length > 0 ? p.name : `arg${i}`;
      return `${name}: ${p.type}`;
    })
    .join(", ");

  // ---- build the return type ----

  const returnType = buildReturnType(spec.outputs);

  // ---- assemble the declaration ----

  // Header: identifies generator, flags as type-only, names the companion impl.
  // The DEC-COMPOSE-BY-REF-DTS-001 reference anchors Future Implementers to the
  // authoritative decision block at the top of this file.
  const header = [
    "// This file is generated by yakcc from the atom SpecYak signature (#1046).",
    "// DEC-COMPOSE-BY-REF-DTS-001 — type-only; no runtime value is present here.",
    "// `yakcc build` materialises the real implementation as the sibling .ts file.",
  ].join("\n");

  const declaration = `export declare function ${symbol}(${paramList}): ${returnType};`;

  return `${header}\n${declaration}\n`;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Derive the TypeScript return-type string from the spec's output parameters.
 *
 * Mapping (DEC-COMPOSE-BY-REF-DTS-001 — simplest faithful representation):
 *   0 outputs → void
 *   1 output  → that output's type
 *   N outputs → tuple [t0, t1, …]
 *
 * Tuple is the simplest correct mapping: it preserves all output types without
 * introducing named-object overhead. A labelled-object form (e.g.
 * `{ char: string }`) would require more context about field naming conventions
 * and is deferred until the spec format has a canonical rule for it.
 */
function buildReturnType(outputs: readonly { readonly type: string }[]): string {
  if (outputs.length === 0) {
    return "void";
  }
  if (outputs.length === 1) {
    const [first] = outputs;
    if (first !== undefined) {
      return first.type;
    }
  }
  // Multiple outputs: emit a positional tuple.
  return `[${outputs.map((o) => o.type).join(", ")}]`;
}
