// SPDX-License-Identifier: MIT
//
// raise-body.ts — render Python AST body nodes (from the libcst envelope) as
// TS-subset IR expressions and statements (WI-782 slice 2b).
//
// Scope: Return, Pass, and a constrained expression subset (Name, Integer,
// Float, String, Bool, None, BinaryOp).  Anything else in the envelope is
// emitted by the Python side as `{type: "Unsupported", reason: <str>}` which
// this module surfaces via UnsupportedAstError — slice 4 wraps in
// CannotRaiseToIRError from @yakcc/contracts.
//
// @decision DEC-POLYGLOT-SHAVE-PY-BODY-RAISE-001 (WI-782 slice 2b)
// @title Body translation pass operates on a structured wire AST, not raw text
// @status accepted (WI-782 slice 2b)
// @rationale
//   An alternative was to keep `body_source` (Python text) and re-parse it on
//   the TS side.  Two reasons against: (1) double-parse cost across files,
//   (2) we'd hand-roll a Python parser in TS, defeating the libcst integration.
//   The libcst pass already walks the AST; we just emit a structured wire
//   shape that this module renders deterministically.

/**
 * Thrown when a wire-AST node carries `{type: "Unsupported"}` — the Python
 * libcst pass encountered a construct outside the slice 2b subset.
 *
 * Slice 4 will reroute these to `CannotRaiseToIRError` from `@yakcc/contracts`
 * with proper location info; for now the message just carries the libcst
 * reason string.
 */
export class UnsupportedAstError extends Error {
  constructor(public readonly reason: string) {
    super(`Unsupported Python construct for raise to TS-subset IR: ${reason}`);
    this.name = "UnsupportedAstError";
  }
}

// ---------------------------------------------------------------------------
// Wire AST types (mirror the JSON shapes emitted by libcst-parse.py)
// ---------------------------------------------------------------------------

export type WireExpr =
  | { readonly type: "Name"; readonly name: string }
  | { readonly type: "Integer"; readonly value: string }
  | { readonly type: "Float"; readonly value: string }
  | { readonly type: "String"; readonly value: string }
  | { readonly type: "Bool"; readonly value: boolean }
  | { readonly type: "None" }
  | {
      readonly type: "BinaryOp";
      readonly op: string;
      readonly left: WireExpr;
      readonly right: WireExpr;
    }
  | { readonly type: "Unsupported"; readonly reason: string };

export type WireStmt =
  | { readonly type: "Return"; readonly value: WireExpr | null }
  | { readonly type: "Pass" }
  | { readonly type: "Unsupported"; readonly reason: string };

// ---------------------------------------------------------------------------
// Renderers
// ---------------------------------------------------------------------------

/** Operators that libcst-parse.py emits as wire-op strings — must match TS. */
const ALLOWED_BINARY_OPS = new Set<string>([
  "+",
  "-",
  "*",
  "/",
  "%",
  "==",
  "!=",
  "<",
  ">",
  "<=",
  ">=",
]);

/** Render a single expression node to TS source text (no trailing semicolon). */
export function renderExpr(expr: WireExpr): string {
  switch (expr.type) {
    case "Name":
      return expr.name;
    case "Integer":
      return expr.value;
    case "Float":
      return expr.value;
    case "String":
      return JSON.stringify(expr.value);
    case "Bool":
      return expr.value ? "true" : "false";
    case "None":
      return "null";
    case "BinaryOp": {
      if (!ALLOWED_BINARY_OPS.has(expr.op)) {
        throw new UnsupportedAstError(`BinaryOp '${expr.op}'`);
      }
      // Always parenthesize to avoid precedence surprises across the
      // Python → TS boundary.  TS source is regenerated by toolchain
      // anyway; reader-friendly precedence is a slice-3+ concern.
      return `(${renderExpr(expr.left)} ${expr.op} ${renderExpr(expr.right)})`;
    }
    case "Unsupported":
      throw new UnsupportedAstError(expr.reason);
  }
}

/** Render a single statement to TS source text (with trailing semicolon). */
export function renderStmt(stmt: WireStmt, indent = "  "): string {
  switch (stmt.type) {
    case "Return": {
      if (stmt.value === null) {
        return `${indent}return;`;
      }
      return `${indent}return ${renderExpr(stmt.value)};`;
    }
    case "Pass":
      // Python's pass has no direct TS equivalent inside a function body.
      // The closest semantic is an empty statement; we emit `void 0;` so
      // the function still compiles when this is the only body content.
      return `${indent}void 0;`;
    case "Unsupported":
      throw new UnsupportedAstError(stmt.reason);
  }
}

/** Render a list of statements joined by newlines. */
export function renderBody(stmts: readonly WireStmt[], indent = "  "): string {
  return stmts.map((s) => renderStmt(s, indent)).join("\n");
}
